### ISSUE TITLE
Unwanted Horizontal Scrollbar at Blog Page

### ISSUE THREAD

**Issue by programmer-rahul** [snipher-marube/blogwebsite#6]
Unwanted Horizontal Scrollbar at Blob Page. It will not give a good user experience.
I can fix this .
Assign me.

[
![Screenshot_20240715_211527](https://github.com/user-attachments/assets/2e0e4732-0041-47e5-a93f-66a668ec1932)
](url)

**Comment by snipher-marube** [comment]
asssigned
